[package]
name = "aws-cli-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.55.3"
aws-sdk-sts = "0.28.0"
aws-types = "0.55.3"
clap = { version = "4.3.9", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.19"
serde_json = "1.0.99"

